services:
  - type: web
    name: socket-io-server-for-nextjs-chat
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
